{{- range $ns := $.Values.namespaces }}
{{- range $key, $val := $.Values.environments }}
{{- if has $ns $val.namespaces }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
 name: allow-env-{{ $key }}
 namespace: {{ $ns }}
spec:
  action: DENY
  rules:
  - from:
    - source:
        notNamespaces:
  {{- range $namespace := $val.namespaces }}
          - {{ $namespace }}
  {{- end }}   
{{- end }}
{{- end }}
{{- end }}